### PR TITLE
[pu-2.0] Creates profile dropdown in navbar

### PR DESCRIPTION
**Pull request by Qayou**
* Adds 'My reports' placeholder dropdown item
* Manages i18n for this dropdown item

### CODE REVIEW

**Comment by Qayou** [comment]
@FranckKe what do you think ? :)

* Not sure what color to set the dropdown button (default color for now)
* Red background for 'Logout'?
* Icons?

profile_navbar

**Comment by FranckKe** [comment]
Looks good!
I would say yes for icons `signed-out` `map-marker-alt` or `map-marked-alt` would work for `my reports`

401 unauthorized happens when not logged and it doesn't update it once logged in.

A solution would be to create a `user` store with user info in `store/module`. 
In the `login` view, update the state when login success (and clear it on logout). 
Import user state getter in menuNav, to display `user.email`.
Might as well use the user state in `Me.vue` too.

**Comment by Qayou** [comment]
- [ ] Create login/logout actions in user.js store
- [ ] Make us of those actions in *Login* and *MenuNav* views/components
- [ ] Make use of the User store in *Me* view

**Comment by FranckKe** [comment]
Rebased.

The user state is stored in `this.$auth.user()` actually. No need to use the store.

- [ ] ~~Create login/logout actions in user.js store~~
- [ ] ~~Make use of those actions in Login and MenuNav views/components~~
- [x]   Make use of the User ~~store~~ auth info in Me view
- [x]  Add Icons (see above comment)

**Pull request merged**
