### PR TITLE
[pu-2.0] Tp clean up rails front (4)

### PR DESCRIPTION
**Pull request by FranckKe**
Remove views
Clean up import/require in css and js
Remove most of assets

### CODE REVIEW

**Comment by mdouchement** [comment]
Rails Admin stuff id linked to #129.
The v1 `/admin/sign_in` does not work work with the incoming PR #126 because we use `ActionController::API` and Rails Admin needs `ActionController::Base` in order to provide devise login form.

We need to dig more in these issues (login and assets) before doing something on Rails Admin's stuff.

**Comment by FranckKe** [comment]
- Flash is not configured in API as far as I know
- Looks like forms are centered  in chromium but not in FF
Reset password form is present but not functional yet as noted

chromium_form
ff_form

**Comment by mdouchement** [comment]
Rails Admin uses the `ActionController::Base` controller and Devise uses its own default controllers. So the Flash message should work.

I'm wondering if the problem comes from the deactivated middlewares. I will take a look.

**Comment by mdouchement** [comment]
It was due to `config.api_only` mode.

@FranckKe The flash message is not closable (there is the close icon but no action associated to)

**Comment by mdouchement** [comment]
The password form still not centered in Chromium like the others

capture d ecran 2018-05-11 a 16 50 33

**Comment by FranckKe** [comment]
Closes #136

**Comment by mdouchement** [comment]
Merged with the next PR #139 😇

**Pull request closed without merging**
